// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: rpc/pb/rpc.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息
type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_pb_rpc_proto_rawDescGZIP(), []int{0}
}

// 响应消息
type PingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=Pong,proto3" json:"Pong,omitempty"`
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_rpc_pb_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type BookId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId string `protobuf:"bytes,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
}

func (x *BookId) Reset() {
	*x = BookId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookId) ProtoMessage() {}

func (x *BookId) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookId.ProtoReflect.Descriptor instead.
func (*BookId) Descriptor() ([]byte, []int) {
	return file_rpc_pb_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *BookId) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type BookInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	PublishBy string   `protobuf:"bytes,2,opt,name=PublishBy,proto3" json:"PublishBy,omitempty"`
	Edition   string   `protobuf:"bytes,3,opt,name=Edition,proto3" json:"Edition,omitempty"`
	Author    string   `protobuf:"bytes,4,opt,name=Author,proto3" json:"Author,omitempty"`
	Values    []*Value `protobuf:"bytes,5,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *BookInfo) Reset() {
	*x = BookInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookInfo) ProtoMessage() {}

func (x *BookInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookInfo.ProtoReflect.Descriptor instead.
func (*BookInfo) Descriptor() ([]byte, []int) {
	return file_rpc_pb_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *BookInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookInfo) GetPublishBy() string {
	if x != nil {
		return x.PublishBy
	}
	return ""
}

func (x *BookInfo) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

func (x *BookInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookInfo) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Large  string `protobuf:"bytes,1,opt,name=Large,proto3" json:"Large,omitempty"`
	Medium string `protobuf:"bytes,2,opt,name=Medium,proto3" json:"Medium,omitempty"`
	Tiny   string `protobuf:"bytes,3,opt,name=tiny,proto3" json:"tiny,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_rpc_pb_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *Image) GetLarge() string {
	if x != nil {
		return x.Large
	}
	return ""
}

func (x *Image) GetMedium() string {
	if x != nil {
		return x.Medium
	}
	return ""
}

func (x *Image) GetTiny() string {
	if x != nil {
		return x.Tiny
	}
	return ""
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price  float32  `protobuf:"fixed32,1,opt,name=Price,proto3" json:"Price,omitempty"`
	Wear   int64    `protobuf:"varint,2,opt,name=wear,proto3" json:"wear,omitempty"`
	Images []*Image `protobuf:"bytes,3,rep,name=Images,proto3" json:"Images,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_rpc_pb_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *Value) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Value) GetWear() int64 {
	if x != nil {
		return x.Wear
	}
	return 0
}

func (x *Value) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

var File_rpc_pb_rpc_proto protoreflect.FileDescriptor

var file_rpc_pb_rpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1f, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x20, 0x0a, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x08, 0x42, 0x6f, 0x6f,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x49,
	0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x61, 0x72, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d,
	0x65, 0x64, 0x69, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6e, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6e, 0x79, 0x22, 0x54, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x65, 0x61, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x77, 0x65, 0x61, 0x72, 0x12, 0x21, 0x0a, 0x06,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x32,
	0x6d, 0x0a, 0x0e, 0x4d, 0x6f, 0x7a, 0x7a, 0x61, 0x72, 0x65, 0x6c, 0x6c, 0x61, 0x42, 0x6f, 0x6f,
	0x6b, 0x12, 0x28, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x42, 0x6f, 0x6f, 0x6b,
	0x49, 0x64, 0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x1a, 0x0c,
	0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x42, 0x1c,
	0x5a, 0x1a, 0x6d, 0x6f, 0x7a, 0x7a, 0x61, 0x72, 0x65, 0x6c, 0x6c, 0x61, 0x2d, 0x62, 0x6f, 0x6f,
	0x6b, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_pb_rpc_proto_rawDescOnce sync.Once
	file_rpc_pb_rpc_proto_rawDescData = file_rpc_pb_rpc_proto_rawDesc
)

func file_rpc_pb_rpc_proto_rawDescGZIP() []byte {
	file_rpc_pb_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_pb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_pb_rpc_proto_rawDescData)
	})
	return file_rpc_pb_rpc_proto_rawDescData
}

var file_rpc_pb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_pb_rpc_proto_goTypes = []interface{}{
	(*PingRequest)(nil), // 0: pb.PingRequest
	(*PingReply)(nil),   // 1: pb.PingReply
	(*BookId)(nil),      // 2: pb.BookId
	(*BookInfo)(nil),    // 3: pb.BookInfo
	(*Image)(nil),       // 4: pb.Image
	(*Value)(nil),       // 5: pb.Value
}
var file_rpc_pb_rpc_proto_depIdxs = []int32{
	5, // 0: pb.BookInfo.Values:type_name -> pb.Value
	4, // 1: pb.Value.Images:type_name -> pb.Image
	0, // 2: pb.MozzarellaBook.Ping:input_type -> pb.PingRequest
	2, // 3: pb.MozzarellaBook.GetBookInfoByBookId:input_type -> pb.BookId
	1, // 4: pb.MozzarellaBook.Ping:output_type -> pb.PingReply
	3, // 5: pb.MozzarellaBook.GetBookInfoByBookId:output_type -> pb.BookInfo
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_pb_rpc_proto_init() }
func file_rpc_pb_rpc_proto_init() {
	if File_rpc_pb_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_pb_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_pb_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_pb_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_pb_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_pb_rpc_proto_msgTypes,
	}.Build()
	File_rpc_pb_rpc_proto = out.File
	file_rpc_pb_rpc_proto_rawDesc = nil
	file_rpc_pb_rpc_proto_goTypes = nil
	file_rpc_pb_rpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MozzarellaBookClient is the client API for MozzarellaBook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MozzarellaBookClient interface {
	// Ping 方法
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	GetBookInfoByBookId(ctx context.Context, in *BookId, opts ...grpc.CallOption) (*BookInfo, error)
}

type mozzarellaBookClient struct {
	cc grpc.ClientConnInterface
}

func NewMozzarellaBookClient(cc grpc.ClientConnInterface) MozzarellaBookClient {
	return &mozzarellaBookClient{cc}
}

func (c *mozzarellaBookClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/pb.MozzarellaBook/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mozzarellaBookClient) GetBookInfoByBookId(ctx context.Context, in *BookId, opts ...grpc.CallOption) (*BookInfo, error) {
	out := new(BookInfo)
	err := c.cc.Invoke(ctx, "/pb.MozzarellaBook/GetBookInfoByBookId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MozzarellaBookServer is the server API for MozzarellaBook service.
type MozzarellaBookServer interface {
	// Ping 方法
	Ping(context.Context, *PingRequest) (*PingReply, error)
	GetBookInfoByBookId(context.Context, *BookId) (*BookInfo, error)
}

// UnimplementedMozzarellaBookServer can be embedded to have forward compatible implementations.
type UnimplementedMozzarellaBookServer struct {
}

func (*UnimplementedMozzarellaBookServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedMozzarellaBookServer) GetBookInfoByBookId(context.Context, *BookId) (*BookInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookInfoByBookId not implemented")
}

func RegisterMozzarellaBookServer(s *grpc.Server, srv MozzarellaBookServer) {
	s.RegisterService(&_MozzarellaBook_serviceDesc, srv)
}

func _MozzarellaBook_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MozzarellaBookServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MozzarellaBook/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MozzarellaBookServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MozzarellaBook_GetBookInfoByBookId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MozzarellaBookServer).GetBookInfoByBookId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MozzarellaBook/GetBookInfoByBookId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MozzarellaBookServer).GetBookInfoByBookId(ctx, req.(*BookId))
	}
	return interceptor(ctx, in, info, handler)
}

var _MozzarellaBook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MozzarellaBook",
	HandlerType: (*MozzarellaBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _MozzarellaBook_Ping_Handler,
		},
		{
			MethodName: "GetBookInfoByBookId",
			Handler:    _MozzarellaBook_GetBookInfoByBookId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/pb/rpc.proto",
}
